### ISSUE TITLE
moment not required

### ISSUE THREAD

**Issue by roberto-belardo** [Requarks/express-brute-loki#3]
There is no require for the moment library used at 79:24 

`lifetime = lifetime ? moment().add(lifetime, 'seconds').toDate() : undefined;`

Adding the following fixes it:

`moment = require('moment');`

Moreover this line should became like this to avoid a warning:

`lifetime = lifetime ? moment().add(lifetime, 'seconds').toDate() : undefined;`

**Comment by NGPixel** [comment]
Fixed.
